apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-zcybavnm
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-zcybavnm:53dfcb67230505bf7a9fab46e40ef3756255fdc7@sha256:6e8c77f17dec3166546c965d486f407e72d68002fbb543ad29541470fd892e02
          name: container-image
